# Generated by Django 4.0.5 on 2022-06-27 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Dulce', 'Dulce'), ('Salado', 'Salado'), ('Vegetariano', 'Vegetariano'), ('Desayunos', 'Desayunos'), ('Sopas', 'Sopas')], max_length=512)),
                ('ingredientes', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='files\x07rchivos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
