# Generated by Django 4.0.5 on 2022-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categoria',
            field=models.CharField(choices=[('Dulce', 'Dulce'), ('Salado', 'Salado'), ('Vegetariano', 'Vegetariano'), ('Desayunos', 'Desayunos'), ('Sopas', 'Sopas')], default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='files\x07rchivos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='recipes',
        ),
    ]
